<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="63376" started-at="2021-03-23T17:04:06 CDT" finished-at="2021-03-23T17:05:09 CDT">
    <groups>
    </groups>
    <test name="Test" duration-ms="63376" started-at="2021-03-23T17:04:06 CDT" finished-at="2021-03-23T17:05:09 CDT">
      <class name="Automation.Test3">
        <test-method status="PASS" signature="SetUpTest()[pri:0, instance:Automation.Test3@5a4aa2f2]" name="SetUpTest" is-config="true" duration-ms="8603" started-at="2021-03-23T17:04:12 CDT" finished-at="2021-03-23T17:04:21 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpTest -->
        <test-method status="PASS" signature="BeginTest()[pri:0, instance:Automation.Test3@5a4aa2f2]" name="BeginTest" duration-ms="20788" started-at="2021-03-23T17:04:28 CDT" finished-at="2021-03-23T17:04:49 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Testing for Exception] but found [Test 3: Preparing for test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Testing for Exception] but found [Test 3: Preparing for test]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Automation.Test3.BeginTest(Test3.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeginTest -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:Automation.Test3@5a4aa2f2]" name="AfterTest" is-config="true" duration-ms="8996" started-at="2021-03-23T17:05:00 CDT" finished-at="2021-03-23T17:05:09 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- Automation.Test3 -->
      <class name="Automation.Test1">
        <test-method status="PASS" signature="SetUpTest()[pri:0, instance:Automation.Test1@58c1c010]" name="SetUpTest" is-config="true" duration-ms="6259" started-at="2021-03-23T17:04:06 CDT" finished-at="2021-03-23T17:04:12 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpTest -->
        <test-method status="PASS" signature="Test()[pri:0, instance:Automation.Test1@58c1c010]" name="Test" duration-ms="7237" started-at="2021-03-23T17:04:21 CDT" finished-at="2021-03-23T17:04:28 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Automation.Test1@58c1c010]" name="afterTest" is-config="true" duration-ms="10897" started-at="2021-03-23T17:04:49 CDT" finished-at="2021-03-23T17:05:00 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Automation.Test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
